# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core import maven_pb2 as maven__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in maven_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DaemonServiceStub(object):
    """Daemon service for background indexing and file watching
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/maven.DaemonService/Ping',
                request_serializer=maven__pb2.PingRequest.SerializeToString,
                response_deserializer=maven__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/maven.DaemonService/GetStatus',
                request_serializer=maven__pb2.StatusRequest.SerializeToString,
                response_deserializer=maven__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StartIndexing = channel.unary_unary(
                '/maven.DaemonService/StartIndexing',
                request_serializer=maven__pb2.IndexRequest.SerializeToString,
                response_deserializer=maven__pb2.IndexResponse.FromString,
                _registered_method=True)
        self.StopIndexing = channel.unary_unary(
                '/maven.DaemonService/StopIndexing',
                request_serializer=maven__pb2.StopRequest.SerializeToString,
                response_deserializer=maven__pb2.StopResponse.FromString,
                _registered_method=True)
        self.GetIndexStats = channel.unary_unary(
                '/maven.DaemonService/GetIndexStats',
                request_serializer=maven__pb2.StatsRequest.SerializeToString,
                response_deserializer=maven__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/maven.DaemonService/Shutdown',
                request_serializer=maven__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=maven__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class DaemonServiceServicer(object):
    """Daemon service for background indexing and file watching
    """

    def Ping(self, request, context):
        """Check if daemon is running
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get daemon status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartIndexing(self, request, context):
        """Start/stop indexing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopIndexing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexStats(self, request, context):
        """Get index stats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Shutdown daemon
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaemonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=maven__pb2.PingRequest.FromString,
                    response_serializer=maven__pb2.PingResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=maven__pb2.StatusRequest.FromString,
                    response_serializer=maven__pb2.StatusResponse.SerializeToString,
            ),
            'StartIndexing': grpc.unary_unary_rpc_method_handler(
                    servicer.StartIndexing,
                    request_deserializer=maven__pb2.IndexRequest.FromString,
                    response_serializer=maven__pb2.IndexResponse.SerializeToString,
            ),
            'StopIndexing': grpc.unary_unary_rpc_method_handler(
                    servicer.StopIndexing,
                    request_deserializer=maven__pb2.StopRequest.FromString,
                    response_serializer=maven__pb2.StopResponse.SerializeToString,
            ),
            'GetIndexStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexStats,
                    request_deserializer=maven__pb2.StatsRequest.FromString,
                    response_serializer=maven__pb2.StatsResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=maven__pb2.ShutdownRequest.FromString,
                    response_serializer=maven__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maven.DaemonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('maven.DaemonService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DaemonService(object):
    """Daemon service for background indexing and file watching
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maven.DaemonService/Ping',
            maven__pb2.PingRequest.SerializeToString,
            maven__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maven.DaemonService/GetStatus',
            maven__pb2.StatusRequest.SerializeToString,
            maven__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartIndexing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maven.DaemonService/StartIndexing',
            maven__pb2.IndexRequest.SerializeToString,
            maven__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopIndexing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maven.DaemonService/StopIndexing',
            maven__pb2.StopRequest.SerializeToString,
            maven__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIndexStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maven.DaemonService/GetIndexStats',
            maven__pb2.StatsRequest.SerializeToString,
            maven__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maven.DaemonService/Shutdown',
            maven__pb2.ShutdownRequest.SerializeToString,
            maven__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
