# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maven.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'maven.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmaven.proto\x12\x05maven\"\r\n\x0bPingRequest\".\n\x0cPingResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t\"\x0f\n\rStatusRequest\"\x7f\n\x0eStatusResponse\x12\x0f\n\x07running\x18\x01 \x01(\x08\x12\x10\n\x08indexing\x18\x02 \x01(\x08\x12\x16\n\x0ewatcher_active\x18\x03 \x01(\x08\x12\x15\n\rfiles_indexed\x18\x04 \x01(\x05\x12\x0e\n\x06uptime\x18\x05 \x01(\t\x12\x0b\n\x03pid\x18\x06 \x01(\x05\"2\n\x0cIndexRequest\x12\x11\n\troot_path\x18\x01 \x01(\t\x12\x0f\n\x07rebuild\x18\x02 \x01(\x08\"1\n\rIndexResponse\x12\x0f\n\x07started\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\r\n\x0bStopRequest\"0\n\x0cStopResponse\x12\x0f\n\x07stopped\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0e\n\x0cStatsRequest\"g\n\rStatsResponse\x12\x12\n\nfile_count\x18\x01 \x01(\x05\x12\x18\n\x10total_size_bytes\x18\x02 \x01(\x03\x12\x17\n\x0flast_indexed_at\x18\x03 \x01(\x01\x12\x0f\n\x07\x64\x62_path\x18\x04 \x01(\t\"\x11\n\x0fShutdownRequest\"5\n\x10ShutdownResponse\x12\x10\n\x08shutdown\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xe8\x02\n\rDaemonService\x12/\n\x04Ping\x12\x12.maven.PingRequest\x1a\x13.maven.PingResponse\x12\x38\n\tGetStatus\x12\x14.maven.StatusRequest\x1a\x15.maven.StatusResponse\x12:\n\rStartIndexing\x12\x13.maven.IndexRequest\x1a\x14.maven.IndexResponse\x12\x37\n\x0cStopIndexing\x12\x12.maven.StopRequest\x1a\x13.maven.StopResponse\x12:\n\rGetIndexStats\x12\x13.maven.StatsRequest\x1a\x14.maven.StatsResponse\x12;\n\x08Shutdown\x12\x16.maven.ShutdownRequest\x1a\x17.maven.ShutdownResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maven_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=22
  _globals['_PINGREQUEST']._serialized_end=35
  _globals['_PINGRESPONSE']._serialized_start=37
  _globals['_PINGRESPONSE']._serialized_end=83
  _globals['_STATUSREQUEST']._serialized_start=85
  _globals['_STATUSREQUEST']._serialized_end=100
  _globals['_STATUSRESPONSE']._serialized_start=102
  _globals['_STATUSRESPONSE']._serialized_end=229
  _globals['_INDEXREQUEST']._serialized_start=231
  _globals['_INDEXREQUEST']._serialized_end=281
  _globals['_INDEXRESPONSE']._serialized_start=283
  _globals['_INDEXRESPONSE']._serialized_end=332
  _globals['_STOPREQUEST']._serialized_start=334
  _globals['_STOPREQUEST']._serialized_end=347
  _globals['_STOPRESPONSE']._serialized_start=349
  _globals['_STOPRESPONSE']._serialized_end=397
  _globals['_STATSREQUEST']._serialized_start=399
  _globals['_STATSREQUEST']._serialized_end=413
  _globals['_STATSRESPONSE']._serialized_start=415
  _globals['_STATSRESPONSE']._serialized_end=518
  _globals['_SHUTDOWNREQUEST']._serialized_start=520
  _globals['_SHUTDOWNREQUEST']._serialized_end=537
  _globals['_SHUTDOWNRESPONSE']._serialized_start=539
  _globals['_SHUTDOWNRESPONSE']._serialized_end=592
  _globals['_DAEMONSERVICE']._serialized_start=595
  _globals['_DAEMONSERVICE']._serialized_end=955
# @@protoc_insertion_point(module_scope)
