from typing import Protocol


class LoggerProtocol(Protocol):
    """Protocol for logger interface that tools expect."""

    def debug(self, msg: str, **kwargs) -> None: ...

    def info(self, msg: str, **kwargs) -> None: ...

    def warning(self, msg: str, **kwargs) -> None: ...

    def error(self, msg: str, **kwargs) -> None: ...

    def exception(self, msg: str, **kwargs) -> None: ...
